{
    'name': 'Contact Cleanup',
    'version': '18.0.1.0.0',
    'summary': 'Cleanup contact information',
    "category": "MegaTecnicentro/CleanUp",
    'author': 'Jorge Alberto Quiroz Sierra',
    "website": "https://megatecnicentro.com/",
    "sequence": -280,
    'depends': [
        "contacts",
        "mail",
        "account",
        "purchase",
        "sale",
        "crm",
    ],
    'data': [
        "security/ir.model.access.csv",
        "security/group.xml",
        "views/views_tools_contact.xml",
        "views/menu.xml",
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}  # type: ignore
